//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Cooking
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Product.
    /// </summary>
    //  *** Start programmer edit section *** (Product CustomAttributes)

    //  *** End programmer edit section *** (Product CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ProductE", new string[] {
            "Weight as \'Weight\'",
            "Ingredient as \'Ingredient\'",
            "Ingredient.Name as \'Name\'"}, Hidden=new string[] {
            "Ingredient.Name"})]
    [MasterViewDefineAttribute("ProductE", "Ingredient", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class Product : ICSSoft.STORMNET.DataObject
    {
        
        private double fWeight;
        
        private IIS.Cooking.Ingredient fIngredient;
        
        private IIS.Cooking.Recipe fRecipe;
        
        //  *** Start programmer edit section *** (Product CustomMembers)

        //  *** End programmer edit section *** (Product CustomMembers)

        
        /// <summary>
        /// Weight.
        /// </summary>
        //  *** Start programmer edit section *** (Product.Weight CustomAttributes)

        //  *** End programmer edit section *** (Product.Weight CustomAttributes)
        public virtual double Weight
        {
            get
            {
                //  *** Start programmer edit section *** (Product.Weight Get start)

                //  *** End programmer edit section *** (Product.Weight Get start)
                double result = this.fWeight;
                //  *** Start programmer edit section *** (Product.Weight Get end)

                //  *** End programmer edit section *** (Product.Weight Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Product.Weight Set start)

                //  *** End programmer edit section *** (Product.Weight Set start)
                this.fWeight = value;
                //  *** Start programmer edit section *** (Product.Weight Set end)

                //  *** End programmer edit section *** (Product.Weight Set end)
            }
        }
        
        /// <summary>
        /// Product.
        /// </summary>
        //  *** Start programmer edit section *** (Product.Ingredient CustomAttributes)

        //  *** End programmer edit section *** (Product.Ingredient CustomAttributes)
        [NotNull()]
        public virtual IIS.Cooking.Ingredient Ingredient
        {
            get
            {
                //  *** Start programmer edit section *** (Product.Ingredient Get start)

                //  *** End programmer edit section *** (Product.Ingredient Get start)
                IIS.Cooking.Ingredient result = this.fIngredient;
                //  *** Start programmer edit section *** (Product.Ingredient Get end)

                //  *** End programmer edit section *** (Product.Ingredient Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Product.Ingredient Set start)

                //  *** End programmer edit section *** (Product.Ingredient Set start)
                this.fIngredient = value;
                //  *** Start programmer edit section *** (Product.Ingredient Set end)

                //  *** End programmer edit section *** (Product.Ingredient Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Cooking.Recipe.
        /// </summary>
        //  *** Start programmer edit section *** (Product.Recipe CustomAttributes)

        //  *** End programmer edit section *** (Product.Recipe CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Cooking.Recipe Recipe
        {
            get
            {
                //  *** Start programmer edit section *** (Product.Recipe Get start)

                //  *** End programmer edit section *** (Product.Recipe Get start)
                IIS.Cooking.Recipe result = this.fRecipe;
                //  *** Start programmer edit section *** (Product.Recipe Get end)

                //  *** End programmer edit section *** (Product.Recipe Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Product.Recipe Set start)

                //  *** End programmer edit section *** (Product.Recipe Set start)
                this.fRecipe = value;
                //  *** Start programmer edit section *** (Product.Recipe Set end)

                //  *** End programmer edit section *** (Product.Recipe Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ProductE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ProductE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ProductE", typeof(IIS.Cooking.Product));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Product.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfProduct CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfProduct CustomAttributes)
    public class DetailArrayOfProduct : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Cooking.DetailArrayOfProduct members)

        //  *** End programmer edit section *** (IIS.Cooking.DetailArrayOfProduct members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Product by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Product.
        /// </summary>
        public DetailArrayOfProduct(IIS.Cooking.Recipe fRecipe) : 
                base(typeof(Product), ((ICSSoft.STORMNET.DataObject)(fRecipe)))
        {
        }
        
        public IIS.Cooking.Product this[int index]
        {
            get
            {
                return ((IIS.Cooking.Product)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Cooking.Product dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
