//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Cooking
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Recipe.
    /// </summary>
    //  *** Start programmer edit section *** (Recipe CustomAttributes)

    //  *** End programmer edit section *** (Recipe CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RecipeE", new string[] {
            "Description as \'Description\'",
            "Person as \'Person\'",
            "Person.Name as \'Name\'"})]
    [AssociatedDetailViewAttribute("RecipeE", "Product", "ProductE", true, "", "Product", true, new string[] {
            ""})]
    [View("RecipeL", new string[] {
            "Description as \'Description\'",
            "Person.Name as \'Name\'"})]
    public class Recipe : ICSSoft.STORMNET.DataObject
    {
        
        private string fDescription;
        
        private IIS.Cooking.Person fPerson;
        
        private IIS.Cooking.DetailArrayOfProduct fProduct;
        
        //  *** Start programmer edit section *** (Recipe CustomMembers)

        //  *** End programmer edit section *** (Recipe CustomMembers)

        
        /// <summary>
        /// Description.
        /// </summary>
        //  *** Start programmer edit section *** (Recipe.Description CustomAttributes)

        //  *** End programmer edit section *** (Recipe.Description CustomAttributes)
        [StrLen(255)]
        public virtual string Description
        {
            get
            {
                //  *** Start programmer edit section *** (Recipe.Description Get start)

                //  *** End programmer edit section *** (Recipe.Description Get start)
                string result = this.fDescription;
                //  *** Start programmer edit section *** (Recipe.Description Get end)

                //  *** End programmer edit section *** (Recipe.Description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Recipe.Description Set start)

                //  *** End programmer edit section *** (Recipe.Description Set start)
                this.fDescription = value;
                //  *** Start programmer edit section *** (Recipe.Description Set end)

                //  *** End programmer edit section *** (Recipe.Description Set end)
            }
        }
        
        /// <summary>
        /// Recipe.
        /// </summary>
        //  *** Start programmer edit section *** (Recipe.Person CustomAttributes)

        //  *** End programmer edit section *** (Recipe.Person CustomAttributes)
        [NotNull()]
        public virtual IIS.Cooking.Person Person
        {
            get
            {
                //  *** Start programmer edit section *** (Recipe.Person Get start)

                //  *** End programmer edit section *** (Recipe.Person Get start)
                IIS.Cooking.Person result = this.fPerson;
                //  *** Start programmer edit section *** (Recipe.Person Get end)

                //  *** End programmer edit section *** (Recipe.Person Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Recipe.Person Set start)

                //  *** End programmer edit section *** (Recipe.Person Set start)
                this.fPerson = value;
                //  *** Start programmer edit section *** (Recipe.Person Set end)

                //  *** End programmer edit section *** (Recipe.Person Set end)
            }
        }
        
        /// <summary>
        /// Recipe.
        /// </summary>
        //  *** Start programmer edit section *** (Recipe.Product CustomAttributes)

        //  *** End programmer edit section *** (Recipe.Product CustomAttributes)
        public virtual IIS.Cooking.DetailArrayOfProduct Product
        {
            get
            {
                //  *** Start programmer edit section *** (Recipe.Product Get start)

                //  *** End programmer edit section *** (Recipe.Product Get start)
                if ((this.fProduct == null))
                {
                    this.fProduct = new IIS.Cooking.DetailArrayOfProduct(this);
                }
                IIS.Cooking.DetailArrayOfProduct result = this.fProduct;
                //  *** Start programmer edit section *** (Recipe.Product Get end)

                //  *** End programmer edit section *** (Recipe.Product Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Recipe.Product Set start)

                //  *** End programmer edit section *** (Recipe.Product Set start)
                this.fProduct = value;
                //  *** Start programmer edit section *** (Recipe.Product Set end)

                //  *** End programmer edit section *** (Recipe.Product Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RecipeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RecipeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RecipeE", typeof(IIS.Cooking.Recipe));
                }
            }
            
            /// <summary>
            /// "RecipeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RecipeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RecipeL", typeof(IIS.Cooking.Recipe));
                }
            }
        }
    }
}
